cu13

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -83,33 +83,53 @@ RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel html5li
       12.6.1) CUINDEX=126 ;; \
       12.8.1) CUINDEX=128 ;; \
       12.9.1) CUINDEX=129 ;; \
-      13.0.1) CUINDEX=130 ;; \
+      13.0.2) CUINDEX=130 ;; \
       *) echo "Unsupported CUDA version: $CUDA_VERSION" && exit 1 ;; \
     esac \
  && if [ "$CUDA_VERSION" = "12.6.1" ]; then \
-     python3 -m pip install --no-cache-dir https://github.com/sgl-project/whl/releases/download/v${SGL_KERNEL_VERSION}/sgl_kernel-${SGL_KERNEL_VERSION}+cu124-cp310-abi3-manylinux2014_$(uname -m).whl --force-reinstall --no-deps ; \
-   fi \
-&& if [ "$CUDA_VERSION" = "12.8.1" ] || [ "$CUDA_VERSION" = "12.9.1" ] || [ "$CUDA_VERSION" = "13.0.1" ]; then \
-     python3 -m pip install --no-cache-dir sgl-kernel==${SGL_KERNEL_VERSION} ; \
-   fi \
+      python3 -m pip install --no-cache-dir https://github.com/sgl-project/whl/releases/download/v${SGL_KERNEL_VERSION}/sgl_kernel-${SGL_KERNEL_VERSION}+cu124-cp310-abi3-manylinux2014_$(uname -m).whl --force-reinstall --no-deps ; \
+    fi \
+ && if [ "$CUDA_VERSION" = "12.8.1" ] || [ "$CUDA_VERSION" = "12.9.1" ] || [ "$CUDA_VERSION" = "13.0.2" ]; then \
+      python3 -m pip install --no-cache-dir sgl-kernel==${SGL_KERNEL_VERSION} ; \
+    fi \
  && python3 -m pip install --no-cache-dir -e "python[${BUILD_TYPE}]" --extra-index-url https://download.pytorch.org/whl/cu${CUINDEX} \
- && python3 -m pip install --no-cache-dir nvidia-nccl-cu12==2.27.6 --force-reinstall --no-deps \
+ && if [ "${CUDA_VERSION%%.*}" = "12" ]; then \
+      python3 -m pip install --no-cache-dir nvidia-nccl-cu12==2.28.3 --force-reinstall --no-deps ; \
+    elif [ "${CUDA_VERSION%%.*}" = "13" ]; then \
+      python3 -m pip install --no-cache-dir nvidia-nccl-cu13==2.28.3 --force-reinstall --no-deps ; \
+    else \
+      echo "No NCCL mapping for CUDA_VERSION=${CUDA_VERSION}" && exit 1 ; \
+    fi \
  && FLASHINFER_LOGGING_LEVEL=warning python3 -m flashinfer --download-cubin
+
 
 
 # Download NVSHMEM source files
 # We use Tom's DeepEP fork for GB200 for now
-RUN wget https://developer.download.nvidia.com/compute/redist/nvshmem/3.4.5/source/nvshmem_src_cuda12-all-all-3.4.5.tar.gz && \
-    if [ "$BUILD_TYPE" = "blackwell_aarch64" ]; then \
-      git clone https://github.com/fzyzcjy/DeepEP.git \
-      && cd DeepEP && git checkout 1b14ad661c7640137fcfe93cccb2694ede1220b0 && sed -i 's/#define NUM_CPU_TIMEOUT_SECS 100/#define NUM_CPU_TIMEOUT_SECS 1000/' csrc/kernels/configs.cuh && cd .. ; \
+RUN set -eux; \
+    if [ "${CUDA_VERSION%%.*}" = "13" ]; then \
+      NVSHMEM_TARBALL="nvshmem_src_cuda13-all-all-3.4.5.tar.gz"; \
     else \
-      git clone https://github.com/deepseek-ai/DeepEP.git \
-      && cd DeepEP && git checkout ${DEEPEP_COMMIT} && sed -i 's/#define NUM_CPU_TIMEOUT_SECS 100/#define NUM_CPU_TIMEOUT_SECS 1000/' csrc/kernels/configs.cuh && cd .. ; \
-    fi \
-    && tar -xf nvshmem_src_cuda12-all-all-3.4.5.tar.gz \
-    && mv nvshmem_src nvshmem \
-    && rm -f /sgl-workspace/nvshmem_src_cuda12-all-all-3.4.5.tar.gz
+      NVSHMEM_TARBALL="nvshmem_src_cuda12-all-all-3.4.5.tar.gz"; \
+    fi; \
+    wget "https://developer.download.nvidia.com/compute/redist/nvshmem/3.4.5/source/${NVSHMEM_TARBALL}" && \
+    if [ "$BUILD_TYPE" = "blackwell_aarch64" ]; then \
+      git clone https://github.com/fzyzcjy/DeepEP.git && \
+      cd DeepEP && \
+      git checkout 1b14ad661c7640137fcfe93cccb2694ede1220b0 && \
+      sed -i 's/#define NUM_CPU_TIMEOUT_SECS 100/#define NUM_CPU_TIMEOUT_SECS 1000/' csrc/kernels/configs.cuh && \
+      cd .. ; \
+    else \
+      git clone https://github.com/deepseek-ai/DeepEP.git && \
+      cd DeepEP && \
+      git checkout "${DEEPEP_COMMIT}" && \
+      sed -i 's/#define NUM_CPU_TIMEOUT_SECS 100/#define NUM_CPU_TIMEOUT_SECS 1000/' csrc/kernels/configs.cuh && \
+      cd .. ; \
+    fi && \
+    tar -xf "${NVSHMEM_TARBALL}" && \
+    mv nvshmem_src nvshmem && \
+    # Cleanup tarball
+    rm -f "/sgl-workspace/${NVSHMEM_TARBALL}"
 
 # Build and install NVSHMEM
 RUN cd /sgl-workspace/nvshmem && \
@@ -131,7 +151,7 @@ RUN cd /sgl-workspace/DeepEP && \
       12.6.1) \
         CHOSEN_TORCH_CUDA_ARCH_LIST='9.0' \
         ;; \
-      12.8.1|12.9.1|13.0.1) \
+      12.8.1|12.9.1|13.0.2) \
         CHOSEN_TORCH_CUDA_ARCH_LIST='9.0;10.0' \
         ;; \
       *) \
