temp comment the old code

diff --git a/.github/workflows/pr-test-amd.yml b/.github/workflows/pr-test-amd.yml
--- a/.github/workflows/pr-test-amd.yml
+++ b/.github/workflows/pr-test-amd.yml
@@ -641,7 +641,7 @@ jobs:
           bash scripts/ci/amd_ci_exec.sh -w "/sglang-checkout/test" python3 run_suite.py --hw amd --suite stage-c-test-large-8-gpu-amd-mi35x --auto-partition-id ${{ matrix.part }} --auto-partition-size 3 --timeout-per-file 3600
 
   stage-b-test-large-1-gpu-performance-amd:
-    needs: [check-changes, call-gate, stage-b-test-small-1-gpu-amd, stage-b-test-large-2-gpu-amd]
+    needs: [check-changes, call-gate, stage-b-test-small-1-gpu-amd]
     if: |
       always() &&
       (
@@ -680,179 +680,179 @@ jobs:
         run: |
           bash scripts/ci/amd_ci_exec.sh -w "/sglang-checkout/test" python3 run_suite.py --hw amd --suite stage-b-test-large-1-gpu-performance-amd --auto-partition-id ${{ matrix.part }} --auto-partition-size 3 --timeout-per-file 1200
 
-  performance-test-1-gpu-part-1-amd:
-    needs: [check-changes, stage-a-test-1-amd]
-    if: |
-      always() &&
-      (
-        (inputs.target_stage == 'performance-test-1-gpu-part-1-amd') ||
-        (
-          !inputs.target_stage &&
-          (!failure() && !cancelled()) &&
-          ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
-        )
-      )
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [linux-mi325-gpu-1]
-    runs-on: ${{matrix.runner}}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
+  # performance-test-1-gpu-part-1-amd:
+  #   needs: [check-changes, stage-a-test-1-amd]
+  #   if: |
+  #     always() &&
+  #     (
+  #       (inputs.target_stage == 'performance-test-1-gpu-part-1-amd') ||
+  #       (
+  #         !inputs.target_stage &&
+  #         (!failure() && !cancelled()) &&
+  #         ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
+  #       )
+  #     )
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       runner: [linux-mi325-gpu-1]
+  #   runs-on: ${{matrix.runner}}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
 
-      - name: Ensure VRAM is clear
-        run: bash scripts/ensure_vram_clear.sh rocm
+  #     - name: Ensure VRAM is clear
+  #       run: bash scripts/ensure_vram_clear.sh rocm
 
-      - name: Start CI container
-        run: bash scripts/ci/amd_ci_start_container.sh
-        env:
-          GITHUB_WORKSPACE: ${{ github.workspace }}
+  #     - name: Start CI container
+  #       run: bash scripts/ci/amd_ci_start_container.sh
+  #       env:
+  #         GITHUB_WORKSPACE: ${{ github.workspace }}
 
-      - name: Install dependencies
-        run: bash scripts/ci/amd_ci_install_dependency.sh
+  #     - name: Install dependencies
+  #       run: bash scripts/ci/amd_ci_install_dependency.sh
 
-      - name: Benchmark single latency
-        timeout-minutes: 20
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_one_batch_1gpu.TestBenchOneBatch1GPU.test_bs1_small
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_one_batch_1gpu.TestBenchOneBatch1GPU.test_bs1_default
+  #     - name: Benchmark single latency
+  #       timeout-minutes: 20
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_one_batch_1gpu.TestBenchOneBatch1GPU.test_bs1_small
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_one_batch_1gpu.TestBenchOneBatch1GPU.test_bs1_default
 
-      - name: Benchmark online latency
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_online_latency_default
+  #     - name: Benchmark online latency
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_online_latency_default
 
-      - name: Benchmark online latency (LoRA)
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_lora_online_latency
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_lora_online_latency_with_concurrent_adapter_updates
+  #     - name: Benchmark online latency (LoRA)
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_lora_online_latency
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_lora_online_latency_with_concurrent_adapter_updates
 
-      - name: Benchmark offline throughput
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_default
+  #     - name: Benchmark offline throughput
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_default
 
-      - name: Benchmark offline throughput (Non-streaming, small batch size)
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_non_stream_small_batch_size
+  #     - name: Benchmark offline throughput (Non-streaming, small batch size)
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_non_stream_small_batch_size
 
-  performance-test-1-gpu-part-2-amd:
-    needs: [check-changes, stage-a-test-1-amd]
-    if: |
-      always() &&
-      (
-        (inputs.target_stage == 'performance-test-1-gpu-part-2-amd') ||
-        (
-          !inputs.target_stage &&
-          (!failure() && !cancelled()) &&
-          ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
-        )
-      )
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [linux-mi325-gpu-1]
-    runs-on: ${{matrix.runner}}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
+  # performance-test-1-gpu-part-2-amd:
+  #   needs: [check-changes, stage-a-test-1-amd]
+  #   if: |
+  #     always() &&
+  #     (
+  #       (inputs.target_stage == 'performance-test-1-gpu-part-2-amd') ||
+  #       (
+  #         !inputs.target_stage &&
+  #         (!failure() && !cancelled()) &&
+  #         ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
+  #       )
+  #     )
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       runner: [linux-mi325-gpu-1]
+  #   runs-on: ${{matrix.runner}}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
 
-      - name: Ensure VRAM is clear
-        run: bash scripts/ensure_vram_clear.sh rocm
+  #     - name: Ensure VRAM is clear
+  #       run: bash scripts/ensure_vram_clear.sh rocm
 
-      - name: Start CI container
-        run: bash scripts/ci/amd_ci_start_container.sh
-        env:
-          GITHUB_WORKSPACE: ${{ github.workspace }}
+  #     - name: Start CI container
+  #       run: bash scripts/ci/amd_ci_start_container.sh
+  #       env:
+  #         GITHUB_WORKSPACE: ${{ github.workspace }}
 
-      - name: Install dependencies
-        run: bash scripts/ci/amd_ci_install_dependency.sh
+  #     - name: Install dependencies
+  #       run: bash scripts/ci/amd_ci_install_dependency.sh
 
-      - name: Benchmark offline throughput (w/o RadixAttention)
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_without_radix_cache
+  #     - name: Benchmark offline throughput (w/o RadixAttention)
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_without_radix_cache
 
-      - name: Benchmark offline throughput (w/ Triton)
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_with_triton_attention_backend
+  #     - name: Benchmark offline throughput (w/ Triton)
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part1.TestBenchServing1GPUPart1.test_offline_throughput_with_triton_attention_backend
 
-      - name: Benchmark offline throughput (w/ FP8)
-        timeout-minutes: 15
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_large.TestBenchServing1GPULarge.test_offline_throughput_default_fp8
+  #     - name: Benchmark offline throughput (w/ FP8)
+  #       timeout-minutes: 15
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_large.TestBenchServing1GPULarge.test_offline_throughput_default_fp8
 
-      - name: Benchmark VLM offline throughput
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_vlm_offline_throughput
+  #     - name: Benchmark VLM offline throughput
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_vlm_offline_throughput
 
-      - name: Benchmark VLM online latency
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_vlm_online_latency
+  #     - name: Benchmark VLM online latency
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_vlm_online_latency
 
-  performance-test-1-gpu-part-3-amd:
-    needs: [check-changes, stage-a-test-1-amd]
-    if: |
-      always() &&
-      (
-        (inputs.target_stage == 'performance-test-1-gpu-part-3-amd') ||
-        (
-          !inputs.target_stage &&
-          (!failure() && !cancelled()) &&
-          ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
-        )
-      )
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [linux-mi325-gpu-1]
-    runs-on: ${{matrix.runner}}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
+  # performance-test-1-gpu-part-3-amd:
+  #   needs: [check-changes, stage-a-test-1-amd]
+  #   if: |
+  #     always() &&
+  #     (
+  #       (inputs.target_stage == 'performance-test-1-gpu-part-3-amd') ||
+  #       (
+  #         !inputs.target_stage &&
+  #         (!failure() && !cancelled()) &&
+  #         ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
+  #       )
+  #     )
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       runner: [linux-mi325-gpu-1]
+  #   runs-on: ${{matrix.runner}}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ inputs.pr_head_sha || inputs.ref || github.sha }}
 
-      - name: Ensure VRAM is clear
-        run: bash scripts/ensure_vram_clear.sh rocm
+  #     - name: Ensure VRAM is clear
+  #       run: bash scripts/ensure_vram_clear.sh rocm
 
-      - name: Start CI container
-        run: bash scripts/ci/amd_ci_start_container.sh
-        env:
-          GITHUB_WORKSPACE: ${{ github.workspace }}
+  #     - name: Start CI container
+  #       run: bash scripts/ci/amd_ci_start_container.sh
+  #       env:
+  #         GITHUB_WORKSPACE: ${{ github.workspace }}
 
-      - name: Install dependencies
-        run: bash scripts/ci/amd_ci_install_dependency.sh
+  #     - name: Install dependencies
+  #       run: bash scripts/ci/amd_ci_install_dependency.sh
 
-      - name: Benchmark Scores online latency and throughput
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_score_api_latency_throughput
+  #     - name: Benchmark Scores online latency and throughput
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_score_api_latency_throughput
 
-      - name: Benchmark Scores online latency and throughput (batch size scaling)
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_score_api_batch_scaling
+  #     - name: Benchmark Scores online latency and throughput (batch size scaling)
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_score_api_batch_scaling
 
-      - name: Benchmark Embeddings online latency and throughput
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_embeddings_api_latency_throughput
+  #     - name: Benchmark Embeddings online latency and throughput
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_embeddings_api_latency_throughput
 
-      - name: Benchmark Embeddings online latency and throughput (batch size scaling)
-        timeout-minutes: 10
-        run: |
-          bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_embeddings_api_batch_scaling
+  #     - name: Benchmark Embeddings online latency and throughput (batch size scaling)
+  #       timeout-minutes: 10
+  #       run: |
+  #         bash scripts/ci/amd_ci_exec.sh -w /sglang-checkout/test/registered/perf python3 -m unittest test_bench_serving_1gpu_part2.TestBenchServing1GPUPart2.test_embeddings_api_batch_scaling
 
   performance-test-2-gpu-amd:
     needs: [check-changes, stage-a-test-1-amd]
