[CI] Tiny refactoring sgl-kernel tests

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -256,36 +256,37 @@ jobs:
 
           echo "All benchmark tests completed!"
 
-  sgl-kernel-b200-test:
-    needs: [check-changes, sgl-kernel-build-wheels]
-    if: needs.check-changes.outputs.sgl_kernel == 'true'
-    runs-on: 4-gpu-b200
-    env:
-      RUNNER_LABELS: 4-gpu-b200
-    steps:
-      - uses: actions/checkout@v4
+  # sgl-kernel-b200-test:
+  #   needs: [check-changes, sgl-kernel-build-wheels]
+  #   if: needs.check-changes.outputs.sgl_kernel == 'true'
+  #   runs-on: 4-gpu-b200
+  #   env:
+  #     RUNNER_LABELS: 4-gpu-b200
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Cleanup
-        run: |
-          ls -alh sgl-kernel/dist || true
-          rm -rf sgl-kernel/dist/* || true
+  #     - name: Cleanup
+  #       run: |
+  #         ls -alh sgl-kernel/dist || true
+  #         rm -rf sgl-kernel/dist/* || true
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: sgl-kernel/dist/
-          merge-multiple: true
-          pattern: wheel-python3.10-cuda12.9
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         path: sgl-kernel/dist/
+  #         merge-multiple: true
+  #         pattern: wheel-python3.10-cuda12.9
 
-      - name: Install dependencies
-        run: |
-          CUSTOM_BUILD_SGL_KERNEL=${{needs.check-changes.outputs.sgl_kernel}} IS_BLACKWELL=1 bash scripts/ci/ci_install_dependency.sh
+  #     - name: Install dependencies
+  #       run: |
+  #         CUSTOM_BUILD_SGL_KERNEL=${{needs.check-changes.outputs.sgl_kernel}} IS_BLACKWELL=1 bash scripts/ci/ci_install_dependency.sh
 
-      - name: Run sgl-kernel unit tests on B200
-        timeout-minutes: 30
-        run: |
-          cd sgl-kernel
-          pytest tests/
+  #     - name: Run sgl-kernel unit tests on B200
+  #       timeout-minutes: 30
+  #       run: |
+  #         cd sgl-kernel
+  #         pytest tests/
+
   # Adding a single CUDA13 smoke test to verify that the kernel builds and runs
   # TODO: Add back this test when it can pass on CI
   # cuda13-kernel-smoke-test:
@@ -376,6 +377,33 @@ jobs:
         run: |
           cd python
           pytest -s -v --log-cli-level=INFO sglang/multimodal_gen/test/server/test_server_performance.py
+
+  quantization-test:
+      needs: [check-changes, stage-a-test-1]
+      if: always() && !failure() && !cancelled() &&
+        ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
+      runs-on: 1-gpu-runner
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+
+        - name: Download artifacts
+          if: needs.check-changes.outputs.sgl_kernel == 'true'
+          uses: actions/download-artifact@v4
+          with:
+            path: sgl-kernel/dist/
+            merge-multiple: true
+            pattern: wheel-python3.10-cuda12.9
+
+        - name: Install dependencies
+          run: |
+            CUSTOM_BUILD_SGL_KERNEL=${{needs.check-changes.outputs.sgl_kernel}} bash scripts/ci/ci_install_dependency.sh
+            pip install "bitsandbytes>=0.44.0"
+        - name: Run test
+          timeout-minutes: 30
+          run: |
+            cd test/srt
+            python3 run_suite.py --suite quantization_test
 
   unit-test-backend-1-gpu:
     needs: [check-changes, stage-a-test-1]
@@ -961,11 +989,11 @@ jobs:
         sgl-kernel-unit-test,
         sgl-kernel-mla-test,
         sgl-kernel-benchmark-test,
-        sgl-kernel-b200-test,
 
         multimodal-gen-test,
 
         stage-a-test-1,
+        quantization-test,
         unit-test-backend-1-gpu,
         unit-test-backend-2-gpu,
         unit-test-backend-4-gpu,
