upd

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -530,40 +530,40 @@ jobs:
             --partition-id ${{ matrix.part }} \
             --total-partitions 2
 
-  quantization-test:
-      needs: [check-changes, call-gate, stage-a-test-1]
-      if: |
-        always() &&
-        (
-          (inputs.target_stage == 'quantization-test') ||
-          (
-            !inputs.target_stage &&
-            (github.event_name == 'schedule' || (!failure() && !cancelled())) &&
-            ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
-          )
-        )
-      runs-on: 1-gpu-runner
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v4
+  # quantization-test:
+  #     needs: [check-changes, call-gate, stage-a-test-1]
+  #     if: |
+  #       always() &&
+  #       (
+  #         (inputs.target_stage == 'quantization-test') ||
+  #         (
+  #           !inputs.target_stage &&
+  #           (github.event_name == 'schedule' || (!failure() && !cancelled())) &&
+  #           ((needs.check-changes.outputs.main_package == 'true') || (needs.check-changes.outputs.sgl_kernel == 'true'))
+  #         )
+  #       )
+  #     runs-on: 1-gpu-runner
+  #     steps:
+  #       - name: Checkout code
+  #         uses: actions/checkout@v4
 
-        - name: Download artifacts
-          if: needs.check-changes.outputs.sgl_kernel == 'true'
-          uses: actions/download-artifact@v4
-          with:
-            path: sgl-kernel/dist/
-            merge-multiple: true
-            pattern: wheel-python3.10-cuda12.9
+  #       - name: Download artifacts
+  #         if: needs.check-changes.outputs.sgl_kernel == 'true'
+  #         uses: actions/download-artifact@v4
+  #         with:
+  #           path: sgl-kernel/dist/
+  #           merge-multiple: true
+  #           pattern: wheel-python3.10-cuda12.9
 
-        - name: Install dependencies
-          run: |
-            pip install "bitsandbytes>=0.44.0"
-            CUSTOM_BUILD_SGL_KERNEL=${{needs.check-changes.outputs.sgl_kernel}} bash scripts/ci/ci_install_dependency.sh
-        - name: Run test
-          timeout-minutes: 30
-          run: |
-            cd test/srt
-            python3 run_suite.py --suite quantization_test
+  #       - name: Install dependencies
+  #         run: |
+  #           pip install "bitsandbytes>=0.44.0"
+  #           CUSTOM_BUILD_SGL_KERNEL=${{needs.check-changes.outputs.sgl_kernel}} bash scripts/ci/ci_install_dependency.sh
+  #       - name: Run test
+  #         timeout-minutes: 30
+  #         run: |
+  #           cd test/srt
+  #           python3 run_suite.py --suite quantization_test
 
   unit-test-backend-1-gpu:
     needs: [check-changes, call-gate, stage-a-test-1]
@@ -584,7 +584,7 @@ jobs:
       fail-fast: false
       max-parallel: ${{ fromJson(needs.check-changes.outputs.max_parallel) }}
       matrix:
-        part: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
+        part: [2]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -1305,7 +1305,7 @@ jobs:
 
         stage-a-test-1,
         stage-b-test-small-1-gpu,
-        quantization-test,
+        # quantization-test,
         unit-test-backend-1-gpu,
         unit-test-backend-2-gpu,
         unit-test-backend-4-gpu,
