Update pr-test-npu.yml

diff --git a/.github/workflows/pr-test-npu.yml b/.github/workflows/pr-test-npu.yml
--- a/.github/workflows/pr-test-npu.yml
+++ b/.github/workflows/pr-test-npu.yml
@@ -1,51 +1,55 @@
 name: PR Test (Ascend NPU)
 
 on:
+  push:
+    branches: [ main ]
+    paths:
+      - "python/**"
+      - "scripts/**"
+      - "test/**"
+      - ".github/workflows/pr-test-npu.yml"
   pull_request:
-    types: [ labeled ]
+    branches: [ main ]
+    paths:
+      - "python/**"
+      - "scripts/**"
+      - "test/**"
+      - ".github/workflows/pr-test-npu.yml"
+  workflow_dispatch:
 
-# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
-# declared as "shell: bash -el {0}" on steps that need to be properly activated.
-# It's used to activate ascend-toolkit environment variables.
-defaults:
-  run:
-    shell: bash -el {0}
-
-# only 1 job can runs on static-8-cards
 concurrency:
-  group: static-8-cards
-  cancel-in-progress: false
+  group: pr-test-npu-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  basic-test-8-npu:
-    # pr-test will be triggered when tag 'npu-test'
-    if: ${{ contains(github.event.pull_request.labels.*.name, 'npu-test') }}
-    name: Basic 8 cards test
-    runs-on: npu
-
-    container:
-      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10
-      volumes:
-        - /usr/local/dcmi:/usr/local/dcmi
-        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
-        - /usr/local/Ascend/driver/:/usr/local/Ascend/driver/
-        # Use self-host cache speed up pip and model download
-        - /home/action/.cache:/github/home/.cache/
-      options: >-
-        --device /dev/davinci0
-        --device /dev/davinci1
-        --device /dev/davinci2
-        --device /dev/davinci3
-        --device /dev/davinci4
-        --device /dev/davinci5
-        --device /dev/davinci6
-        --device /dev/davinci7
-        --device /dev/davinci_manager
-        --device /dev/devmm_svm
-        --device /dev/hisi_hdc
+  unit-test-backend-1-npu-ascend:
+    if: (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') &&
+      github.event.pull_request.draft == false  && contains(github.event.pull_request.labels.*.name, 'npu')
+    strategy:
+      fail-fast: false
+    runs-on: self-hosted
     steps:
-      - name: Check npu and CANN info
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run test
+        timeout-minutes: 40
         run: |
-          npu-smi info
-          python3 -m unittest test_ascend_attention_backend.TestAscendAttnBackend.test_gsm8k
-          python3 -m unittest test_ascend_attention_backend.TestAscendAttnBackend.test_latency
+          python3 run_suite.py --suite per-commit-npu
+
+  finish:
+    if: always()
+    needs: [ unit-test-backend-1-npu-ascend ]
+    runs-on: self-hosted
+    steps:
+      - name: Check all dependent job statuses
+        run: |
+          results=(${{ join(needs.*.result, ' ') }})
+          for result in "${results[@]}"; do
+            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
+              echo "Job failed with result: $result"
+              exit 1
+            fi
+          done
+          echo "All jobs completed successfully"
+          exit 0
